apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-07-24T11:57:11Z"
  generation: 1
  labels:
    app: legacy-youtube-web
  name: legacy-youtube-web
  namespace: default
  resourceVersion: "25479"
  selfLink: /apis/apps/v1/namespaces/default/deployments/legacy-youtube-web
  uid: 83d4dd2d-674e-4923-bb67-f504b835527e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: legacy-youtube-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: legacy-youtube-web
    spec:
      containers:
      - image: caprilespe/legacy-youtube-web:v1
        imagePullPolicy: IfNotPresent
        name: legacy-youtube-web
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-07-24T11:57:37Z"
    lastUpdateTime: "2021-07-24T11:57:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-07-24T11:57:11Z"
    lastUpdateTime: "2021-07-24T11:57:37Z"
    message: ReplicaSet "legacy-youtube-web-55dd6f5c84" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
